routes/web.php
Route::get('/car-single/{id}', 'frontend\CarController@car_single')->name('car-single');
Route::post('/car-book', 'frontend\CarController@car_book')->name('car-book');
Route::post('/insert-car-booking', 'frontend\CarController@insert_booking')->name('insert-car-booking');
Route::post('/car-review', 'frontend\CarController@review_post')->name('car-review');

Route::get('/guider-list', 'frontend\GuiderController@guider_list')->name('guider-list');
Route::get('/guider-single/{id}', 'frontend\GuiderController@guider_single')->name('guider-single');
Route::post('/guid-review', 'frontend\GuiderController@review_post')->name('guid-review');


Route::get('/agency-list', 'frontend\TravelAgencyController@agency_list')->name('agency-list');
Route::get('/agency-single/{id}', 'frontend\TravelAgencyController@agency_single')->name('agency-single');
Route::get('/package/details', 'frontend\TravelAgencyController@packages_details')->name('package-details');
Route::post('/package-book', 'frontend\TravelAgencyController@package_book')->name('package-book');
Route::post('/insert-package-booking', 'frontend\TravelAgencyController@insert_booking')->name('insert-package-booking');
Route::post('/travel-review', 'frontend\TravelAgencyController@review_post')->name('travel-review');


Route::get('/restaurant-list', 'frontend\RestaurantController@restaurant_list')->name('restaurant-list');
Route::get('/restaurant-single/{id}', 'frontend\RestaurantController@restaurant_single')->name('restaurant-single');
Route::post('/restaurant-review', 'frontend\RestaurantController@review_post')->name('restaurant-review');


Route::get('/districts-list', 'frontend\HomeController@districts_list')->name('districts-list');

Route::get('wislist', 'frontend\WishlistController@wislistSave')->name('wislist-save');
Route::get('wishlist', 'frontend\WishlistController@wishlist')->name('wishlist');

Route::get('/add-listing', 'frontend\HomeController@add_listing')->name('add-listing');
Route::get('/customer-profile', 'frontend\HomeController@customer_profile')->name('customer-profile');
Route::get('/listing-view', 'frontend\HomeController@listing_view')->name('listing-view');
Route::get('/listing-booking', 'frontend\HomeController@listing_booking')->name('listing-booking');
Route::get('/customer-review', 'frontend\HomeController@customer_review')->name('customer-review');
Route::get('/customer-edit-profile', 'frontend\HomeController@customer_edit_profile')->name('customer-edit-profile');
Route::post('/add-booking', 'frontend\HomeController@add_booking')->name('add-booking');
Route::post('/insert-booking', 'frontend\HomeController@insert_booking')->name('insert-booking');
Route::get('/rooms/details', 'frontend\HomeController@rooms_details')->name('rooms-details');



Auth::routes();

Route::group(['middleware' => ['auth']], function () {
Route::get('/add-businessstep1', 'frontend\AccountController@add_businessstep1')->name('add-businessstep1');
Route::post('/add-businessstep1', 'frontend\AccountController@create_businessstep1')->name('add-businessstep1');

Route::get('/add-businessstep2', 'frontend\AccountController@add_businessstep2')->name('add-businessstep2');
Route::post('/add-businessstep2', 'frontend\AccountController@create_businessstep2')->name('add-businessstep2');

Route::get('/add-businessstep3', 'frontend\AccountController@add_businessstep3')->name('add-businessstep3');
Route::post('/add-businessstep3', 'frontend\AccountController@create_businessstep3')->name('add-businessstep3');


Route::post('/add-businessstep-yourself', 'frontend\AccountController@create_yourself_businessstep')->name('add-businessstep-yourself');

Route::get('myform/ajax/{id}',array('as'=>'myform.ajax','uses'=>'AccountController@myformAjax'));

Route::get('/user-dashboard', 'frontend\UserDashboardController@user_dashboard')->name('user-dashboard');
Route::get('/user-accommodation/index', 'frontend\UserAccommodationController@index')->name('user-accommodation.index');
Route::get('/user-accommodation/view/{id}', 'frontend\UserAccommodationController@view')->name('user-accommodation.view');
    Route::post('/user-accommodation/store', 'frontend\UserAccommodationController@store_rooms')->name('user-accommodation.add-rooms');
    Route::post('projects/media', 'frontend\UserAccommodationController@storeMedia')
        ->name('projects.storeMedia');
});
Route::post('/user-accommodation/update/{id}', 'frontend\UserAccommodationController@update_rooms')->name('user-accommodation.update-rooms');
Route::get('/user-accommodation/destroy/{id}', 'frontend\UserAccommodationController@destroy_image')->name('user-accommodation.destroyimage');
Route::get('/user-accommodation/destroyroom/{id}', 'frontend\UserAccommodationController@destroy_room')->name('user-accommodation.destroyroom');
Route::get('/user-accommodation/destroyacc/{id}', 'frontend\UserAccommodationController@destroy_acc')->name('user-accommodation.acc_destroy');


Route::get('/user-restaurant/index', 'frontend\UserRestaurantController@index')->name('user-restaurant.index');
Route::get('/user-guider/index', 'frontend\UserGuiderController@index')->name('user-guider.index');
Route::get('/user-agency/index', 'frontend\UserAgencyController@index')->name('user-agency.index');


Route::get('/auth/redirect/{provider}', 'SocialController@redirect');
Route::get('/callback/{provider}', 'SocialController@callback');

Route::post('/edit-profile/update/{id}', 'frontend\UserProfileController@editprofile')->name('edit-profile.update');
Route::get('/status/update', 'frontend\UserProfileController@updateStatus')->name('users.update.status');

Route::group(['middleware' => ['role_or_permission:Super Admin|Hotel Owner|Restaurant Owner|Agency Owner|Guider|Car Renter', 'auth']], function () {
	Route::get('/dashboard', 'backend\HomeController@index')->name('home');
      Route::resource('roles','backend\RoleController');
    Route::resource('users','backend\UserController');
    Route::resource('permissions','backend\PermissionController');
    Route::resource('blogs','backend\BlogController');
    Route::get('blogchangeStatus', 'backend\BlogController@changeStatus');

    //accommodation route
    Route::resource('accommodations','backend\AccommodationController');
    Route::get('/accommodations/imagedelete/{id}', 'backend\AccommodationController@images_destroy')->name('accommodation.delete-images');
    Route::get('accommodationchangeStatus', 'backend\AccommodationController@changeStatus');
    Route::resource('accommodation-rooms','backend\AccommodationRoomController');
    Route::get('/accommodations-room/imagedelete/{id}', 'backend\AccommodationRoomController@images_destroy')->name('accommodation-room.delete-images');
    Route::get('accommodationroomchangeStatus', 'backend\AccommodationRoomController@changeStatus');
    Route::get('accommodationdistrict', 'backend\AccommodationController@dependancydistrict');
    Route::resource('accomodation-booking','backend\AccomodationBookingController');
    Route::get('accbookStatus', 'backend\AccomodationBookingController@changeStatus');

    //car route
    Route::resource('cars','backend\CarController');
    Route::get('carchangeStatus', 'backend\CarController@changeStatus');
    Route::resource('car-booking','backend\CarBookingController');
    Route::get('carbookStatus', 'backend\CarBookingController@changeStatus');
    Route::get('/car/imagedelete/{id}', 'backend\CarController@images_destroy')->name('car.delete-images');

    //agency route
    Route::resource('travel-agencies','backend\TravelAgencyController');
    Route::get('agencychangeStatus', 'backend\TravelAgencyController@changeStatus');
    Route::get('travelagencies/create', 'backend\TravelAgencyController@check_slug')->name('agencies.check_slug');
    Route::resource('tour-packages','backend\TourPackageController');
    Route::get('packagesStatus', 'backend\TourPackageController@changeStatus');
    Route::get('tour-packages/create', 'backend\TourPackageController@check_slug')->name('package.check_slug');
    Route::resource('package-booking','backend\PackageBookingController');
    Route::get('packagebookStatus', 'backend\PackageBookingController@changeStatus');
    Route::get('/tour/imagedelete/{id}', 'backend\TourPackageController@images_destroy')->name('tour.delete-images');

    //Restaurant
    Route::resource('restaurants','backend\RestaurantController');
    Route::get('restaurant/create', 'backend\RestaurantController@check_slug')->name('restaurant.check_slug');
    Route::get('restaurantStatus', 'backend\RestaurantController@changeStatus');
    Route::get('/restaurant/imagedelete/{id}', 'backend\RestaurantController@images_destroy')->name('restaurant.delete-images');


    //Restaurant Item route
    Route::resource('items','backend\ItemController');
    Route::get('item/create', 'backend\ItemController@check_slug')->name('item.check_slug');
    Route::get('itemStatus', 'backend\ItemController@changeStatus');
    Route::get('/items/imagedelete/{id}', 'backend\ItemController@images_destroy')->name('items.delete-images');


    //Location route
    Route::resource('locations','backend\LocationController');
    Route::get('city_search', 'backend\LocationController@citysearch');

    //Guiders route
    Route::resource('guiders','backend\GuiderController');
    Route::get('guiderdistrict', 'backend\GuiderController@dependancydistrict');
    Route::get('guiderchangeStatus', 'backend\GuiderController@changeStatus');

    //giuderdetails
    Route::resource('guider-details','backend\GuiderDetailsController');
    Route::get('travelStatus', 'backend\GuiderDetailsController@changeStatus');
    Route::get('/traveldetail/imagedelete/{id}', 'backend\GuiderDetailsController@images_destroy')->name('traveldetail.delete-images');

    //Review route
    Route::get('reviews/hotels', 'backend\ReviewController@hotel')->name('reviews.hotels');

    //USER Profile
    Route::get('user/profile', 'backend\ProfileController@index')->name('profile.index');

app/Http/Controllers/backend/AccomodationBookingController.php
<?php

namespace App\Http\Controllers\backend;

use App\AccommodationBooking;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class AccomodationBookingController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:hotel-booking-list|hotel-booking-create|hotel-booking-edit|hotel-booking-delete', ['only' => ['index', 'store']]);
        $this->middleware('permission:hotel-booking-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:hotel-booking-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:hotel-booking-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $booking = AccommodationBooking::withoutGlobalScopes();
        if (Auth::user()->hasRole(['Admin','Super Admin'])) {
            $booking->with('room')->orderBy('id', 'desc');
        }else {
            $booking->whereHas('room.accommodation', function ($q) {
                $q->where('user_id',Auth::id());
            });
        }
        $booking = $booking->get();

        return view('backend.accomodation-booking.index',compact('booking'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }
    public function changeStatus(Request $request)
    {
        $user = AccommodationBooking::find($request->booking_id);
        $user->approve = $request->approve;
        $user->save();

        return response()->json(['success'=>'Status change successfully.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = AccommodationBooking::findorfail($id);
        $blog->delete();
        return redirect()->route('accomodation-booking.index')
            ->with('success','Hotel Booking deleted successfully');
    }
}

app/Http/Controllers/backend/BlogController.php
<?php

namespace App\Http\Controllers\backend;

use App\Blog;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BlogController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:blog-list|blog-create|blog-edit|blog-delete', ['only' => ['index','store']]);
        $this->middleware('permission:blog-create', ['only' => ['create','store']]);
        $this->middleware('permission:blog-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:blog-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (Auth::user()->hasRole(['Admin', 'Super Admin'])) {
            $blogs = Blog::withoutGlobalScopes()->orderBy('id', 'desc')->get();
        } else{
            $blogs = Blog::orderBy('id', 'desc')->get();
        }
        //dd($roles);
        return view('backend.blogs.index',compact('blogs'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.blogs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'image' => 'required',
        ]);
        $user_id = Auth::id();

        $blog = Blog::create(['title' => $request->input('title'),
            'description' => $request->input('description'),
            'user_id' => $user_id,
        ]);

        $file = $request->file('image');

        if (!empty($file)) {
            $destinationPath = 'uploads/blog/';
            $filename = $file->getClientOriginalName();
            $file->move($destinationPath, $filename);
            $blog->image = $destinationPath . $filename;
            $blog->save();
        }

        return redirect()->route('blogs.index')
            ->with('success','Blog created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog = Blog::withoutGlobalScopes()->find($id);
        return view('backend.blogs.show',compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog = Blog::withoutGlobalScopes()->find($id);


        return view('backend.blogs.edit',compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',

        ]);


        $blog = Blog::withoutGlobalScopes()->find($id);

        $blog->title = $request->input('title');
        $blog->description = $request->input('description');
        $file = $request->file('image');

        if (!empty($file)) {
            $destinationPath = 'uploads/blog/';
            $filename = $file->getClientOriginalName();
            $file->move(public_path('uploads/blog/'), $filename);
            $blog->image = $destinationPath . $filename;
        }

        $blog->update();

        return redirect()->route('blogs.index')
            ->with('success','Blog updated successfully');
    }

    public function changeStatus(Request $request)
    {
        $user = Blog::withoutGlobalScopes()->find($request->blog_id);
        $user->publish_status = $request->publish_status;
        $user->save();

        return response()->json(['success'=>'Status change successfully.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = Blog::withoutGlobalScopes()->find($id);
        $blog->delete();
//        dd($blog);
        toastr()->success('Blog Delete Successful!');
        return redirect()->route('blogs.index');
    }
}

resources/views/backend/accommodations/index.blade.php
@extends('backend.layouts.master')
@section('content')

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
                <h3 class="page-title">
                    Hotel table
                </h3>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Tables</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Hotel table</li>
                    </ol>
                </nav>
            </div>
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title"> Hotel List</h4>
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <table id="order-listing" class="table">
                                    <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Title</th>
                                        <th>Email</th>
                                        <th>Contact No</th>
                                        <th>Address</th>
                                        @can('hotel-publish')
                                        <th>Status</th>
                                        @endcan
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($accommodations as $key => $accommodation)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            <td>{{ $accommodation->title }}</td>
                                            <td>{{ $accommodation->email }}</td>
                                            <td>{{ $accommodation->contact_number }}</td>
                                            <td>{{ $accommodation->address }}</td>
                                            @can('hotel-publish')
                                            <td>
                                                <input data-id="{{$accommodation->id}}" class="toggle-class" type="checkbox" data-onstyle="success" data-offstyle="danger" data-toggle="toggle" data-on="Active" data-off="InActive" {{ $accommodation->publish_status ? 'checked' : '' }}>
                                            </td>
                                            @endcan
                                            <td>
                                                @can('hotel-room')
                                                <a class="btn btn-outline-success" style="margin-bottom: 2px" href="{{ route('accommodation-rooms.show',$accommodation->id) }}">Add Rooms</a>
                                                @endcan
                                                @can('hotel-view')
                                                <a class="btn btn-outline-primary" href="{{ route('accommodations.show',$accommodation->id) }}">View</a>
                                                @endcan
                                                @can('hotel-edit')
                                                    <a class="btn btn-outline-info" href="{{ route('accommodations.edit',$accommodation->id) }}">Edit</a>
                                                @endcan
                                                @can('hotel-delete')
                                                    {!! Form::open(['method' => 'DELETE','route' => ['accommodations.destroy', $accommodation->id],'style'=>'display:inline']) !!}
                                                    {!! Form::submit('Delete', ['class' => 'btn btn-outline-danger','data-toggle'=>'confirmation']) !!}
                                                    {!! Form::close() !!}
                                                @endcan
                                            </td>
                                        </tr>
                                    @endforeach


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @can('hotel-create')
            <a href="{{ route('accommodations.create') }}">
                <div class="theme-setting-wrapper">
                    <div id="settings-trigger"><i class="fas fa-plus"> </i></div>
                </div></a>
        @endcan
        @section('scripts')
            <script src="{{asset('backend/js/data-table.js')}}"></script>
            <script>
  $(function() {
    $('.toggle-class').change(function() {
        var publish_status = $(this).prop('checked') == true ? 1 : 0;
        var accommodation_id = $(this).data('id');

        $.ajax({
            type: "GET",
            dataType: "json",
            url: '/accommodationchangeStatus',
            data: {'publish_status': publish_status, 'accommodation_id': accommodation_id},
            success: function(data){
             toastr.success('Review successfully');
              console.log(data.success)


        },
        error: function (msg) {
            toastr.error( 'Inconceivable!');
        }
        });
    })
  })
</script>
@endsection

@endsection

resources/views/backend/accommodations/show.blade.php
@extends('backend.layouts.master')
@section('content')

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
                <h3 class="page-title">
                    View Accommodation
                </h3>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">View</a></li>
                        <li class="breadcrumb-item active" aria-current="page">View Accommodation</li>
                    </ol>
                </nav>
            </div>

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>type:</strong>
                                    {!! $accommodation->types->name !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>title:</strong>
                                    {{ $accommodation->title }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>contact_number:</strong>
                                    {{ $accommodation->contact_number }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Email:</strong>
                                    {{ $accommodation->email }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>address:</strong>
                                    {{ $accommodation->address }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>location:</strong>
                                    {{ $accommodation->location }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>description:</strong>
                                    {!! $accommodation->description  !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>check_in:</strong>
                                    {{ $accommodation->check_in }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>check_out:</strong>
                                    {{ $accommodation->check_out }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>price:</strong>
                                    {{ $accommodation->price }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>website:</strong>
                                    {{ $accommodation->website_link }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>facebook:</strong>
                                    {{ $accommodation->fb_page_link }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>instergram:</strong>
                                    {{ $accommodation->instergram_link }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>twiter:</strong>
                                    {{ $accommodation->twiter_link }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>term condition:</strong>
                                    {!! $accommodation->term_condition !!}
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>facilities:</strong>

                                        @foreach($accommodation->facilities as $v)
                                            <label class="badge badge-success">{{ $v->name }}</label>
                                        @endforeach

                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>services:</strong>

                                        @foreach($accommodation->services as $vs)
                                            <label class="badge badge-success">{{ $vs->name }}</label>
                                        @endforeach

                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Images:</strong>

                                        @foreach($accommodation->images as $vs)
                                            <img src="{{ asset($vs->accommodation_image) }}" style="width: auto;height: 100px;">
                                        @endforeach

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <!-- <h2> Show User</h2> -->
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('accommodations.index') }}"> Back</a>
                    </div>
                </div>
            </div>




@endsection