routes/web.php
Route::get('/car-single/{id}', 'frontend\CarController@car_single')->name('car-single');
Route::post('/car-book', 'frontend\CarController@car_book')->name('car-book');
Route::post('/insert-car-booking', 'frontend\CarController@insert_booking')->name('insert-car-booking');
Route::post('/car-review', 'frontend\CarController@review_post')->name('car-review');

Route::get('/guider-list', 'frontend\GuiderController@guider_list')->name('guider-list');
Route::get('/guider-single/{id}', 'frontend\GuiderController@guider_single')->name('guider-single');
Route::post('/guid-review', 'frontend\GuiderController@review_post')->name('guid-review');


Route::get('/agency-list', 'frontend\TravelAgencyController@agency_list')->name('agency-list');
Route::get('/agency-single/{id}', 'frontend\TravelAgencyController@agency_single')->name('agency-single');
Route::get('/package/details', 'frontend\TravelAgencyController@packages_details')->name('package-details');
Route::post('/package-book', 'frontend\TravelAgencyController@package_book')->name('package-book');
Route::post('/insert-package-booking', 'frontend\TravelAgencyController@insert_booking')->name('insert-package-booking');
Route::post('/travel-review', 'frontend\TravelAgencyController@review_post')->name('travel-review');


Route::get('/restaurant-list', 'frontend\RestaurantController@restaurant_list')->name('restaurant-list');
Route::get('/restaurant-single/{id}', 'frontend\RestaurantController@restaurant_single')->name('restaurant-single');
Route::post('/restaurant-review', 'frontend\RestaurantController@review_post')->name('restaurant-review');


Route::get('/districts-list', 'frontend\HomeController@districts_list')->name('districts-list');

Route::get('wislist', 'frontend\WishlistController@wislistSave')->name('wislist-save');
Route::get('wishlist', 'frontend\WishlistController@wishlist')->name('wishlist');

Route::get('/add-listing', 'frontend\HomeController@add_listing')->name('add-listing');
Route::get('/customer-profile', 'frontend\HomeController@customer_profile')->name('customer-profile');
Route::get('/listing-view', 'frontend\HomeController@listing_view')->name('listing-view');
Route::get('/listing-booking', 'frontend\HomeController@listing_booking')->name('listing-booking');
Route::get('/customer-review', 'frontend\HomeController@customer_review')->name('customer-review');
Route::get('/customer-edit-profile', 'frontend\HomeController@customer_edit_profile')->name('customer-edit-profile');
Route::post('/add-booking', 'frontend\HomeController@add_booking')->name('add-booking');
Route::post('/insert-booking', 'frontend\HomeController@insert_booking')->name('insert-booking');
Route::get('/rooms/details', 'frontend\HomeController@rooms_details')->name('rooms-details');



Auth::routes();

Route::group(['middleware' => ['auth']], function () {
Route::get('/add-businessstep1', 'frontend\AccountController@add_businessstep1')->name('add-businessstep1');
Route::post('/add-businessstep1', 'frontend\AccountController@create_businessstep1')->name('add-businessstep1');

Route::get('/add-businessstep2', 'frontend\AccountController@add_businessstep2')->name('add-businessstep2');
Route::post('/add-businessstep2', 'frontend\AccountController@create_businessstep2')->name('add-businessstep2');

Route::get('/add-businessstep3', 'frontend\AccountController@add_businessstep3')->name('add-businessstep3');
Route::post('/add-businessstep3', 'frontend\AccountController@create_businessstep3')->name('add-businessstep3');


Route::post('/add-businessstep-yourself', 'frontend\AccountController@create_yourself_businessstep')->name('add-businessstep-yourself');

Route::get('myform/ajax/{id}',array('as'=>'myform.ajax','uses'=>'AccountController@myformAjax'));

Route::get('/user-dashboard', 'frontend\UserDashboardController@user_dashboard')->name('user-dashboard');
Route::get('/user-accommodation/index', 'frontend\UserAccommodationController@index')->name('user-accommodation.index');
Route::get('/user-accommodation/view/{id}', 'frontend\UserAccommodationController@view')->name('user-accommodation.view');
    Route::post('/user-accommodation/store', 'frontend\UserAccommodationController@store_rooms')->name('user-accommodation.add-rooms');
    Route::post('projects/media', 'frontend\UserAccommodationController@storeMedia')
        ->name('projects.storeMedia');
});
Route::post('/user-accommodation/update/{id}', 'frontend\UserAccommodationController@update_rooms')->name('user-accommodation.update-rooms');
Route::get('/user-accommodation/destroy/{id}', 'frontend\UserAccommodationController@destroy_image')->name('user-accommodation.destroyimage');
Route::get('/user-accommodation/destroyroom/{id}', 'frontend\UserAccommodationController@destroy_room')->name('user-accommodation.destroyroom');
Route::get('/user-accommodation/destroyacc/{id}', 'frontend\UserAccommodationController@destroy_acc')->name('user-accommodation.acc_destroy');


Route::get('/user-restaurant/index', 'frontend\UserRestaurantController@index')->name('user-restaurant.index');
Route::get('/user-guider/index', 'frontend\UserGuiderController@index')->name('user-guider.index');
Route::get('/user-agency/index', 'frontend\UserAgencyController@index')->name('user-agency.index');


Route::get('/auth/redirect/{provider}', 'SocialController@redirect');
Route::get('/callback/{provider}', 'SocialController@callback');

Route::post('/edit-profile/update/{id}', 'frontend\UserProfileController@editprofile')->name('edit-profile.update');
Route::get('/status/update', 'frontend\UserProfileController@updateStatus')->name('users.update.status');

Route::group(['middleware' => ['role_or_permission:Super Admin|Hotel Owner|Restaurant Owner|Agency Owner|Guider|Car Renter', 'auth']], function () {
	Route::get('/dashboard', 'backend\HomeController@index')->name('home');
      Route::resource('roles','backend\RoleController');
    Route::resource('users','backend\UserController');
    Route::resource('permissions','backend\PermissionController');
    Route::resource('blogs','backend\BlogController');
    Route::get('blogchangeStatus', 'backend\BlogController@changeStatus');

    //accommodation route
    Route::resource('accommodations','backend\AccommodationController');
    Route::get('/accommodations/imagedelete/{id}', 'backend\AccommodationController@images_destroy')->name('accommodation.delete-images');
    Route::get('accommodationchangeStatus', 'backend\AccommodationController@changeStatus');
    Route::resource('accommodation-rooms','backend\AccommodationRoomController');
    Route::get('/accommodations-room/imagedelete/{id}', 'backend\AccommodationRoomController@images_destroy')->name('accommodation-room.delete-images');
    Route::get('accommodationroomchangeStatus', 'backend\AccommodationRoomController@changeStatus');
    Route::get('accommodationdistrict', 'backend\AccommodationController@dependancydistrict');
    Route::resource('accomodation-booking','backend\AccomodationBookingController');
    Route::get('accbookStatus', 'backend\AccomodationBookingController@changeStatus');

    //car route
    Route::resource('cars','backend\CarController');
    Route::get('carchangeStatus', 'backend\CarController@changeStatus');
    Route::resource('car-booking','backend\CarBookingController');
    Route::get('carbookStatus', 'backend\CarBookingController@changeStatus');
    Route::get('/car/imagedelete/{id}', 'backend\CarController@images_destroy')->name('car.delete-images');

    //agency route
    Route::resource('travel-agencies','backend\TravelAgencyController');
    Route::get('agencychangeStatus', 'backend\TravelAgencyController@changeStatus');
    Route::get('travelagencies/create', 'backend\TravelAgencyController@check_slug')->name('agencies.check_slug');
    Route::resource('tour-packages','backend\TourPackageController');
    Route::get('packagesStatus', 'backend\TourPackageController@changeStatus');
    Route::get('tour-packages/create', 'backend\TourPackageController@check_slug')->name('package.check_slug');
    Route::resource('package-booking','backend\PackageBookingController');
    Route::get('packagebookStatus', 'backend\PackageBookingController@changeStatus');
    Route::get('/tour/imagedelete/{id}', 'backend\TourPackageController@images_destroy')->name('tour.delete-images');

    //Restaurant
    Route::resource('restaurants','backend\RestaurantController');
    Route::get('restaurant/create', 'backend\RestaurantController@check_slug')->name('restaurant.check_slug');
    Route::get('restaurantStatus', 'backend\RestaurantController@changeStatus');
    Route::get('/restaurant/imagedelete/{id}', 'backend\RestaurantController@images_destroy')->name('restaurant.delete-images');


    //Restaurant Item route
    Route::resource('items','backend\ItemController');
    Route::get('item/create', 'backend\ItemController@check_slug')->name('item.check_slug');
    Route::get('itemStatus', 'backend\ItemController@changeStatus');
    Route::get('/items/imagedelete/{id}', 'backend\ItemController@images_destroy')->name('items.delete-images');


    //Location route
    Route::resource('locations','backend\LocationController');
    Route::get('city_search', 'backend\LocationController@citysearch');

    //Guiders route
    Route::resource('guiders','backend\GuiderController');
    Route::get('guiderdistrict', 'backend\GuiderController@dependancydistrict');
    Route::get('guiderchangeStatus', 'backend\GuiderController@changeStatus');

    //giuderdetails
    Route::resource('guider-details','backend\GuiderDetailsController');
    Route::get('travelStatus', 'backend\GuiderDetailsController@changeStatus');
    Route::get('/traveldetail/imagedelete/{id}', 'backend\GuiderDetailsController@images_destroy')->name('traveldetail.delete-images');

    //Review route
    Route::get('reviews/hotels', 'backend\ReviewController@hotel')->name('reviews.hotels');

    //USER Profile
    Route::get('user/profile', 'backend\ProfileController@index')->name('profile.index');

app/Http/Controllers/backend/AccomodationBookingController.php
<?php

namespace App\Http\Controllers\backend;

use App\AccommodationBooking;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class AccomodationBookingController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:hotel-booking-list|hotel-booking-create|hotel-booking-edit|hotel-booking-delete', ['only' => ['index', 'store']]);
        $this->middleware('permission:hotel-booking-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:hotel-booking-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:hotel-booking-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $booking = AccommodationBooking::withoutGlobalScopes();
        if (Auth::user()->hasRole(['Admin','Super Admin'])) {
            $booking->with('room')->orderBy('id', 'desc');
        }else {
            $booking->whereHas('room.accommodation', function ($q) {
                $q->where('user_id',Auth::id());
            });
        }
        $booking = $booking->get();

        return view('backend.accomodation-booking.index',compact('booking'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }
    public function changeStatus(Request $request)
    {
        $user = AccommodationBooking::find($request->booking_id);
        $user->approve = $request->approve;
        $user->save();

        return response()->json(['success'=>'Status change successfully.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = AccommodationBooking::findorfail($id);
        $blog->delete();
        return redirect()->route('accomodation-booking.index')
            ->with('success','Hotel Booking deleted successfully');
    }
}

app/Http/Controllers/backend/BlogController.php
<?php

namespace App\Http\Controllers\backend;

use App\Blog;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BlogController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:blog-list|blog-create|blog-edit|blog-delete', ['only' => ['index','store']]);
        $this->middleware('permission:blog-create', ['only' => ['create','store']]);
        $this->middleware('permission:blog-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:blog-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (Auth::user()->hasRole(['Admin', 'Super Admin'])) {
            $blogs = Blog::withoutGlobalScopes()->orderBy('id', 'desc')->get();
        } else{
            $blogs = Blog::orderBy('id', 'desc')->get();
        }
        //dd($roles);
        return view('backend.blogs.index',compact('blogs'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.blogs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'image' => 'required',
        ]);
        $user_id = Auth::id();

        $blog = Blog::create(['title' => $request->input('title'),
            'description' => $request->input('description'),
            'user_id' => $user_id,
        ]);

        $file = $request->file('image');

        if (!empty($file)) {
            $destinationPath = 'uploads/blog/';
            $filename = $file->getClientOriginalName();
            $file->move($destinationPath, $filename);
            $blog->image = $destinationPath . $filename;
            $blog->save();
        }

        return redirect()->route('blogs.index')
            ->with('success','Blog created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog = Blog::withoutGlobalScopes()->find($id);
        return view('backend.blogs.show',compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog = Blog::withoutGlobalScopes()->find($id);


        return view('backend.blogs.edit',compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',

        ]);


        $blog = Blog::withoutGlobalScopes()->find($id);

        $blog->title = $request->input('title');
        $blog->description = $request->input('description');
        $file = $request->file('image');

        if (!empty($file)) {
            $destinationPath = 'uploads/blog/';
            $filename = $file->getClientOriginalName();
            $file->move(public_path('uploads/blog/'), $filename);
            $blog->image = $destinationPath . $filename;
        }

        $blog->update();

        return redirect()->route('blogs.index')
            ->with('success','Blog updated successfully');
    }

    public function changeStatus(Request $request)
    {
        $user = Blog::withoutGlobalScopes()->find($request->blog_id);
        $user->publish_status = $request->publish_status;
        $user->save();

        return response()->json(['success'=>'Status change successfully.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = Blog::withoutGlobalScopes()->find($id);
        $blog->delete();
//        dd($blog);
        toastr()->success('Blog Delete Successful!');
        return redirect()->route('blogs.index');
    }
}

resources/views/backend/roles/create.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
                <h3 class="page-title">
                    Create User
                </h3>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Forms</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create User</li>
                    </ol>
                </nav>
            </div>
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Create User</h4>

                        {!! Form::open(array('route' => 'roles.store','method'=>'POST')) !!}
                        <div class="form-group">
                            <label for="exampleInputName1">Name</label>
                            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail3">Permission</label><br>
                             @foreach($permission as $value)
                                <label>{{ Form::checkbox('permission[]', $value->id, false, array('class' => 'name')) }}
                                    {{ $value->name }}</label>
                                <br/>
                            @endforeach
                        </div>

                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>






   @endsection

resources/views/backend/roles/edit.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
                <h3 class="page-title">
                    Edit Role
                </h3>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Forms</a></li>
                        <li class="breadcrumb-item active" aria-current="page"> Edit Role</li>
                    </ol>
                </nav>
            </div>
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title"> Edit Role</h4>

                        {!! Form::model($role, ['method' => 'PATCH','route' => ['roles.update', $role->id]]) !!}
                        <div class="form-group">
                            <label for="exampleInputName1">Name</label>
                            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail3">Permission</label><br>
                            @foreach($permission as $value)
                                <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}
                                    {{ $value->name }}</label>
                                <br/>
                            @endforeach
                        </div>

                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>





   @endsection

resources/views/backend/roles/index.blade.php
@extends('backend.layouts.master')
@section('content')

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
                <h3 class="page-title">
                    User Role table
                </h3>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Tables</a></li>
                        <li class="breadcrumb-item active" aria-current="page">User Role table</li>
                    </ol>
                </nav>
            </div>
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">User Role List</h4>
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <table id="order-listing" class="table">
                                    <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($roles as $key => $role)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            <td>{{ $role->name }}</td>
                                            <td>
                                                <a class="btn btn-outline-primary" href="{{ route('roles.show',$role->id) }}">View</a>
                                                @can('role-edit')
                                                    <a class="btn btn-outline-info" href="{{ route('roles.edit',$role->id) }}">Edit</a>
                                                @endcan
                                                @can('role-delete')
                                                    {!! Form::open(['method' => 'DELETE','route' => ['roles.destroy', $role->id],'style'=>'display:inline']) !!}
                                                    {!! Form::submit('Delete', ['class' => 'btn btn-outline-danger','data-toggle'=>'confirmation']) !!}
                                                    {!! Form::close() !!}
                                                @endcan
                                            </td>
                                        </tr>
                                    @endforeach


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @can('role-create')
        <a href="{{ route('roles.create') }}">
            <div class="theme-setting-wrapper">
                <div id="settings-trigger"><i class="fas fa-plus"> </i></div>
            </div></a>
        @endcan
        @section('scripts')
            <script src="{{asset('backend/js/data-table.js')}}"></script>
        @endsection

@endsection

resources/views/backend/roles/show.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
                <h3 class="page-title">
                    View Role
                </h3>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">View</a></li>
                        <li class="breadcrumb-item active" aria-current="page">View Role</li>
                    </ol>
                </nav>
            </div>

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    {{ $role->name }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Permissions:</strong>
                                    @if(!empty($rolePermissions))
                                        @foreach($rolePermissions as $v)
                                            <label class="label label-success">{{ $v->name }},</label>
                                        @endforeach
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <!-- <h2> Show User</h2> -->
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
                    </div>
                </div>
            </div>



@endsection